export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN = 'LOGIN';

export const USER_INFO_LOADING = 'USER_INFO_LOADING';
export const USER_INFO = 'USER_INFO';

export const GET_RESTAURANT_LIST = 'GET_RESTAURANT_LIST';
export const GET_RESTAURANT_LIST_MORE = 'GET_RESTAURANT_LIST_MORE';
export const GET_RESTAURANT_LIST_LOADING = 'GET_RESTAURANT_LIST_LOADING';

export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const GET_ORDER_LIST_MORE = 'GET_ORDER_LIST_MORE';
export const GET_ORDER_LIST_LOADING = 'GET_ORDER_LIST_LOADING';
